import { CLIENTS } from "@/data/clients";
import { ALL_PROJECTS, PORTFOLIO } from "@/data/portfolio";
import { PARTNERS } from "@/data/partners";
import { SERVICES } from "@/data/services";
import { CONTACTS } from "@/data/contacts";
import type { SiteContent } from "./types";

const ADVANTAGES = [
  {
    id: "turnkey",
    icon: "turnkey" as const,
    title: "Полный цикл работ «под ключ»",
    shortTitle: "Под ключ",
    lead: "Берём на себя всё — от идеи до сдачи готового объекта.",
    text: "Вам не нужно искать проектировщиков, производство и монтажную бригаду отдельно. Мы ведём проект единой командой: согласуем конструкцию, изготавливаем на своём производстве, доставляем и монтируем на объекте. Сроки, качество и ответственность — на одной стороне.",
    highlights: ["Единый подрядчик на все этапы", "Прозрачная смета без скрытых работ", "Сдача объекта в оговорённые сроки"],
  },
  {
    id: "production",
    icon: "design" as const,
    title: "Производство полного цикла",
    shortTitle: "Полный цикл",
    lead: "Собственный проектный отдел, цех и склад — всё в одном месте.",
    text: "Проектируем конструкции под ваш объект, производим на собственном оборудовании и комплектуем со склада. Партнёрство с заводами-поставщиками позволяет подбирать оптимальные материалы и держать цены без лишних наценок посредников.",
    highlights: ["Собственный проектный отдел", "Производственный цех и склад", "Прямые поставки от заводов"],
  },
  {
    id: "license",
    icon: "license" as const,
    title: "Государственная строительная лицензия",
    shortTitle: "Лицензия",
    lead: "Работаем официально — с полным пакетом документов.",
    text: "Лицензия подтверждает право на все виды работ. Заключаем договор, предоставляем акты и гарантийные обязательства — без посредников и серых схем.",
    highlights: ["Лицензия на все виды работ", "Официальный договор и акты", "Без посредников"],
  },
  {
    id: "measure",
    icon: "measure" as const,
    title: "Бесплатный выезд, замер и расчёт проекта",
    shortTitle: "Бесплатный замер",
    lead: "Инженер приедет на объект, снимет размеры и подготовит расчёт — бесплатно.",
    text: "Выезд и замер не обязывают к заказу. Специалист осмотрит объект, уточнит задачу, предложит варианты конструкций и материалов. Вы получите понятную смету и сроки — до принятия решения о сотрудничестве.",
    highlights: ["Расчёт стоимости без обязательств"],
  },
];

const PROCESS_STEPS = [
  { id: "step-1", num: "01", title: "Заявка и консультация", text: "Обсуждаем задачу, объект, материалы, сроки" },
  { id: "step-2", num: "02", title: "Выезд, замер и расчёт", text: "Бесплатный выезд и замер. Готовим проект и смету" },
  {
    id: "step-3",
    num: "03",
    title: "Производство и монтаж",
    text: "Изготавливаем, привозим, монтируем, сдаём с ",
    highlight: "гарантией 5 лет",
  },
];

export const DEFAULT_CONTENT: SiteContent = {
  version: 1,
  updatedAt: new Date().toISOString(),
  meta: {
    title: "ART OFFICE GROUP — стекло, алюминий, металл",
    titleTemplate: "%s | ART OFFICE GROUP",
    description:
      "ART OFFICE GROUP — производство и монтаж стеклянных конструкций, витражей, перегородок и фасадов в Алматы и по Казахстану.",
    ogTitle: "ART OFFICE GROUP — остекление под ключ",
    ogDescription:
      "Производство и монтаж стеклянных конструкций, витражей, перегородок и фасадов в Алматы и области.",
    siteUrl: "https://art-office.kz",
  },
  branding: {
    companyName: "ART OFFICE GROUP",
    logo: "/images/log.png",
  },
  header: {
    navLinks: [
      { href: "#services", label: "Услуги" },
      { href: "#portfolio", label: "Проекты" },
      { href: "#clients", label: "Клиенты" },
      { href: "#partners", label: "Наши партнеры" },
      { href: "#contacts", label: "Контакты" },
    ],
    ctaButton: "Заказать звонок",
  },
  hero: {
    enabled: true,
    poster: "/assets/hero-poster.jpg",
    video: "/assets/hero.mp4",
    badge: "16 лет · Алматы",
    title: "Профессиональное остекление",
    titleAccent: "под ключ",
    subtitle1: "Собственное производство и монтаж в Алматы",
    subtitle2: "Бесплатный выезд и замер",
    ctaPrimary: "Бесплатный замер",
    yearsCount: "16",
    yearsLabel: "лет на рынке",
    scrollHint: "Листайте",
  },
  homeSections: {
    order: ["services", "advantages", "portfolio", "clients", "partners", "process", "contacts"],
    services: {
      enabled: true,
      label: "Направления",
      title: "Что мы производим и монтируем",
      items: SERVICES.map((s) => ({
        id: s.id,
        title: s.title,
        description: s.description,
        icon: s.icon,
        image: s.placeholderImage ?? `/images/services/${s.id}.jpg`,
      })),
      extraOption: "Другое",
    },
    advantages: {
      enabled: true,
      label: "Преимущества",
      title: "Почему с нами работают",
      items: ADVANTAGES,
    },
    portfolio: {
      enabled: true,
      label: "Портфолио",
      title: "Реализованные проекты",
      ctaText: "Смотреть проекты",
      ctaLink: "/projects",
      galleryButton: "Смотреть галерею",
      allProjectsLabel: "Все объекты",
      items: ALL_PROJECTS.map((p) => ({
        id: p.id,
        name: p.name,
        type: p.type,
        cover: p.cover,
        gallery: p.gallery,
        showOnHome: PORTFOLIO.some((home) => home.id === p.id),
      })),
    },
    clients: {
      enabled: true,
      label: "Клиенты",
      title: "Нам доверяют",
      ctaText: "Все клиенты",
      ctaLink: "/clients",
      items: CLIENTS.map((c, i) => ({
        id: `client-${i}`,
        name: c.name,
        src: c.src,
        category: c.category,
        highlight: c.highlight,
      })),
    },
    partners: {
      enabled: true,
      label: "Партнёры",
      title: "Наши партнеры",
      subtitle: "Производители и поставщики материалов, которые мы применяем в производстве",
      ctaText: "Все партнёры",
      ctaLink: "/partners",
      items: PARTNERS.map((p, i) => ({
        id: `partner-${i}`,
        name: p.name,
        src: p.src,
      })),
    },
    process: {
      enabled: true,
      label: "Процесс",
      title: "От заявки до сдачи проекта",
      accent: "— 3 шага",
      items: PROCESS_STEPS,
    },
    contacts: {
      enabled: true,
      label: "Контакты",
      title: "Оставьте заявку — рассчитаем проект бесплатно",
      formTitle: "Бесплатный расчёт проекта",
      formSubtitle: "Перезвоним в рабочее время и обсудим детали",
      submitButton: "Отправить заявку",
      whatsappButton: "Написать в WhatsApp",
    },
  },
  contacts: {
    company: CONTACTS.company,
    address: CONTACTS.address,
    addressMeta: CONTACTS.addressMeta,
    mapCoordinates: { ...CONTACTS.mapCoordinates },
    phonePrimary: CONTACTS.phonePrimary,
    phoneSecondary: CONTACTS.phoneSecondary,
    phonePrimaryHref: CONTACTS.phonePrimaryHref,
    phoneSecondaryHref: CONTACTS.phoneSecondaryHref,
    email: CONTACTS.email,
    whatsappPhone: CONTACTS.whatsappPhone,
    whatsappMessage: CONTACTS.whatsappMessage,
    hours: CONTACTS.hours,
    instagram: "https://www.instagram.com/artofficegroup/",
  },
  footer: {
    year: 2026,
    location: "Алматы · Казахстан",
    copyrightSuffix: "Все права защищены.",
  },
  pages: {
    projects: {
      title: "Проекты",
      description: "Реализованные проекты ART OFFICE GROUP — остекление, фасады, перегородки в Алматы.",
      label: "Портфолио",
      heading: "Все реализованные проекты",
    },
    clients: {
      title: "Клиенты",
      description: "Компании, которые доверили ART OFFICE GROUP остекление и монтаж.",
      label: "Клиенты",
      heading: "Нам доверяют ведущие компании",
    },
    partners: {
      title: "Партнёры",
      description: "Производители и поставщики материалов ART OFFICE GROUP.",
      label: "Партнёры",
      heading: "Наши партнёры",
    },
  },
  kz: {
    contacts: {
      whatsappMessage: "Сәлеметсіз бе! Шынылау бойынша кеңес алғым келеді.",
      company: 'ТОО «ART OFFICE GROUP»',
      address: "Алматы қ., Сырбayı Мауленов к-сі, 111, 2-кеңсе",
      addressMeta: "Алмалы ауданы, 050012",
      hours: "Дс–Жм, 9:00–18:00",
    },
    header: {
      navLinks: [
        { href: "#services", label: "Қызметтер" },
        { href: "#portfolio", label: "Жобалар" },
        { href: "#clients", label: "Клиенттер" },
        { href: "#partners", label: "Серіктестеріміз" },
        { href: "#contacts", label: "Байланыс" },
      ],
      ctaButton: "Кері қоңырауға тапсырыс",
    },
    hero: {
      badge: "16 жыл · Алматы",
      title: "Кілтпен тапсырылатын кәсіби шынылау",
      titleAccent: "",
      subtitle1: "Алматыдағы меншікті өндіріс пен монтаждау жұмыстары",
      subtitle2: "Тегін өлшеу жұмыстары",
      ctaPrimary: "Есептеуге тапсырыс беру",
      yearsLabel: "жыл нарықта",
      scrollHint: "Төмен қарай",
    },
    homeSections: {
      services: {
        label: "Бағыттар",
        title: "Біз өндіретін және орнататын конструкциялар",
        extraOption: "Басқа",
        items: [
          { title: "Қалқалар", description: "Шыны, алюминий, өртке төзімді және жылжымалы қалқалар" },
          { title: "Есіктер", description: "Шыны, алюминий, металл және автоматты есіктер" },
          { title: "Терезелер", description: "Тұрғын және коммерциялық нысандарға арналған алюминий терезелер" },
          { title: "Витраждар мен қасбеттер", description: "Қасбеттік шынылау және витраж жүйелері" },
          { title: "Қоршау жүйелері", description: "Баспалдақ, балкон және террасаларға арналған шыны қоршаулар" },
          { title: "Шыны күнқағарлар", description: "Күнқағарлар, шыны едендер, айналар және басқа конструкциялар" },
          { title: "Шыны душ кабиналары", description: "Өлшемге сай жасалатын шыны душ кабиналары, қалқалар және қоршаулар" },
          { title: "Жобалау", description: "Өз жобалау бөліміміз және өндіруші зауыттармен серіктестік" },
        ],
      },
      advantages: {
        label: "Артықшылықтар",
        title: "Неліктен бізді таңдайды",
        items: [
          {
            title: "Кілтпен тапсырылатын жұмыстардың толық циклі",
            shortTitle: "Кілтпен тапсыру",
            lead: "Барлық жұмысты өз мойнымызға аламыз: идеядан бастап дайын нысанды тапсыруға дейін.",
            text: "Жобалаушыларды, өндірісті және монтаждау бригадасын бөлек іздеудің қажеті жоқ. Біз жобаны бірыңғай командамен жүргіземіз: конструкцияны келісеміз, өз өндірісімізде дайындаймыз, нысанға жеткіземіз және монтаждаймыз. Мерзім, сапа және жауапкершілік — бір тарапта.",
            highlights: ["Барлық кезеңге арналған бірыңғай мердігер", "Жасырын шығындарсыз ашық смета", "Нысанды келісілген мерзімде тапсыру"],
          },
          {
            title: "Толық циклді өндіріс",
            shortTitle: "Толық цикл",
            lead: "Меншікті жобалау бөлімі, цех және қойма — бәрі бір жерде.",
            text: "Конструкцияларды нысаныңызға сай жобалаймыз, өз жабдығымызда өндіреміз және қоймадан жинақтаймыз. Өндіруші зауыттармен серіктестік оңтайлы материалдарды таңдауға және делдалдардың үстеме бағасынсыз тиімді бағаны сақтауға мүмкіндік береді.",
            highlights: ["Меншікті жобалау бөлімі", "Өндірістік цех пен қойма", "Зауыттардан тікелей жеткізу"],
          },
          {
            title: "Мемлекеттік құрылыс лицензиясы",
            shortTitle: "Лицензия",
            lead: "Ресми түрде жұмыс істейміз және құжаттардың толық пакетін ұсынамыз.",
            text: "Лицензия барлық жұмыс түрлерін орындау құқығын растайды. Келісімшарт жасасып, актілер мен кепілдік міндеттемелерін береміз — делдалдарсыз және жасырын схемаларсыз.",
            highlights: ["Барлық жұмыс түріне лицензия", "Ресми келісімшарт пен актілер", "Делдалдарсыз"],
          },
          {
            title: "Нысанға тегін бару, өлшеу және жобаны есептеу",
            shortTitle: "Тегін өлшеу",
            lead: "Инженер нысанға барып, өлшем алып, есепті тегін дайындайды.",
            text: "Нысанға бару мен өлшеу тапсырыс беруге міндеттемейді. Маман нысанды қарап, тапсырманы нақтылайды, конструкциялар мен материалдардың нұсқаларын ұсынады. Ынтымақтастық туралы шешім қабылдамай тұрып, түсінікті смета мен мерзімді аласыз.",
            highlights: ["Құнын міндеттемесіз есептеу"],
          },
        ],
      },
      portfolio: {
        label: "Портфолио",
        title: "Орындалған жобалар",
        ctaText: "Жобаларды көру",
        galleryButton: "Галереяны көру",
        allProjectsLabel: "Барлық нысандар",
        items: [
          { type: "Шоурум" },
          { type: "Қонақ үй" },
          { type: "Сауда кешені" },
          { type: "Кешен" },
          { type: "Мейрамхана" },
          { type: "Мейрамхана" },
          { type: "Бизнес орталық" },
          { type: "Тұрғын үй кешені" },
          { type: "Сауда орталығы" },
          { type: "Кеңсе" },
          { type: "Мейрамхана" },
          { type: "Қонақ үй" },
          { type: "Медициналық орталық" },
          { type: "Банк" },
          { type: "Спорт нысаны" },
          { type: "Тұрғын үй" },
          { type: "Салон" },
          { type: "Білім беру нысаны" },
        ],
      },
      clients: {
        label: "Клиенттер",
        title: "Бізге сенеді",
        ctaText: "Барлық клиенттер",
        items: [
          {
            category: "Автокөлік саласы",
            highlight: "Премиум дилерлік орталыққа арналған шынылау және қасбет жұмыстары",
          },
          {
            category: "HoReCa",
            highlight: "Жылдам тамақтану мейрамханаларына арналған шыны шешімдер",
          },
          {
            category: "Мұнай және энергетика",
            highlight: "Отын-энергетика нысандарына арналған конструкциялар",
          },
          {
            category: "Сауда орталығы",
            highlight: "Сауда кешендеріне арналған витраждар мен қасбеттік шынылау",
          },
          {
            category: "Қонақүй бизнесі",
            highlight: "Люкс санатындағы қонақүйлерге арналған панорамалық шынылау және қалқалар",
          },
          {
            category: "Автокөлік саласы",
            highlight: "Автосалонға арналған архитектуралық шынылау",
          },
          {
            category: "Автокөлік саласы",
            highlight: "Шыны қасбеттер мен кіреберіс аймақтары",
          },
          {
            category: "Қонақүй бизнесі",
            highlight: "Қонақүй кешеніне арналған жеке конструкциялар",
          },
          {
            category: "Сауда орталығы",
            highlight: "Сауда нысанына арналған шынылау және металл конструкциялар",
          },
          {
            category: "Ритейл",
            highlight: "Бренд аймағына арналған шыны қалқалар мен витриналар",
          },
          {
            category: "Автокөлік саласы",
            highlight: "Қасбеттік және интерьерлік шыны жүйелері",
          },
          {
            category: "Автокөлік саласы",
            highlight: "Өкілдік салонға арналған премиум шынылау",
          },
        ],
      },
      partners: {
        label: "Серіктестер",
        title: "Серіктестеріміз",
        subtitle: "Өндірісте қолданылатын материалдарды өндірушілер мен жеткізушілер",
        ctaText: "Барлық серіктестер",
      },
      process: {
        label: "Процесс",
        title: "Өтінімнен дайын нысанды\nтапсырғанға дейін",
        accent: "— 3 қадам",
        items: [
          { title: "Өтінім және кеңес беру", text: "Тапсырманы, нысанды, материалдарды және мерзімді талқылаймыз" },
          { title: "Маманның шығуы, өлшеуі және есептеу", text: "Маманның тегін шығуы және өлшеуі. Жоба мен сметаны дайындаймыз" },
          { title: "Өндіріс және монтаж", text: "Дайындаймыз, жеткіземіз, орнатамыз және 10 жылға дейінгі кепілдікпен тапсырамыз", highlight: null },
        ],
      },
      contacts: {
        label: "Байланыс",
        title: "Өтінім қалдырыңыз — жобаңызды тегін есептеп береміз",
        formTitle: "Жобаны тегін есептеу",
        formSubtitle: "Жұмыс уақытында хабарласып, мәліметтерді нақтылаймыз",
        submitButton: "Өтінім қалдыру",
        whatsappButton: "WhatsApp арқылы жазу",
      },
    },
    footer: {
      location: "Алматы · Қазақстан",
      copyrightSuffix: "Барлық құқықтар қорғалған.",
    },
    pages: {
      projects: {
        title: "Жобалар",
        description: "ART OFFICE GROUP орындаған жобалар: Алматыдағы шынылау, қасбеттер және қалқалар.",
        label: "Портфолио",
        heading: "Барлық орындалған жобалар",
      },
      clients: {
        title: "Клиенттер",
        description: "Шынылау және монтаж жұмыстарын ART OFFICE GROUP-қа сеніп тапсырған компаниялар.",
        label: "Клиенттер",
        heading: "Бізге жетекші компаниялар сенеді",
      },
      partners: {
        title: "Серіктестер",
        description: "ART OFFICE GROUP жұмыс істейтін материал өндірушілер мен жеткізушілер.",
        label: "Серіктестер",
        heading: "Серіктестеріміз",
      },
    },
  },
};
